name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex build-essential libssl-dev libncurses5-dev python3

    - name: Setup directories
      run: |
        mkdir -p out

    - name: Generate kernel config
      run: |
        export ARCH=arm
        make -C kernel O=../out lineage_trelteskt_defconfig

    - name: Disable missing bcmdhd4358_100
      run: |
        sed -i '/CONFIG_BCMDHD4358_100/d' out/.config
        echo "# CONFIG_BCMDHD4358_100 is not set" >> out/.config

        echo "Current bcmdhd config:"
        grep BCMDHD out/.config || true

    - name: Build kernel
      run: |
        export ARCH=arm
        export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchain/bin/arm-linux-androideabi-

        make -C kernel O=../out olddefconfig
        make -C kernel O=../out -j$(nproc)

    - name: Upload kernel image
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: out/arch/arm/boot/zImage
