name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          make \
          git \
          wget \
          xz-utils

    - name: Download GCC 4.9 Linaro toolchain
      run: |
        wget https://releases.linaro.org/components/toolchain/binaries/4.9-2017.01/arm-linux-gnueabi/gcc-linaro-4.9-2017.01-x86_64_arm-linux-gnueabi.tar.xz
        tar xf gcc-linaro-4.9-2017.01-x86_64_arm-linux-gnueabi.tar.xz

    - name: Clone kernel
      run: |
        git clone --depth=1 \
        -b lineage-21.0 \
        https://github.com/retiredcrave/android_kernel_samsung_exynos5420.git kernel

    - name: Build kernel
      run: |
        export ARCH=arm
        export CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-linaro-4.9-2017.01-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-

        cd kernel

        make lineageos_ha3g_defconfig

        make -j$(nproc) zImage
